import type { Metadata } from "next";
import { MyQueryClientProvider } from "@/providers/query-client";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MyQueryClientProvider>{children}</MyQueryClientProvider>
      </body>
    </html>
  );
}
