import type { Metadata } from "next";
import { MyQueryClientProvider } from "@/providers/query-client";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <MyQueryClientProvider>{children}</MyQueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
